[package]
name = "chronoutil"
version = "0.1.0"
authors = ["olliemath <oliver@suade.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"chrono" = "^0.4"
